### ISSUE TITLE
Infografía_SDLC_Daisy_Gonzalez_Lita

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-1-infografia-Daisy-GonzalezLita12#1]
Infografía 
[SDLC_DAISY_GONZALEZ_LITA.pdf](https://github.com/user-attachments/files/16820211/SDLC_DAISY_GONZALEZ_LITA.pdf)

**Comment by Nancy-0714** [comment]
Bien hecho, obtuviste 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
